swagger: '2.0'
info:
  title: Energydash API
  description: Energy monitoring data accessible through an API
  version: 1.0.0
  license:
    name: MIT
  contact:
    name: Chris Linstid
    url: 'https://github.com/clinstid/energydash-node'

paths:
  /readings:
    x-swagger-router-controller: readings
    get:
      operationId: GetReadings

      description: |
        Retrieve a list of energy readings filtered by the specified query
        parameters.

      produces:
        - application/json

      parameters:
        - $ref: '#/parameters/StartDateQueryParam'
        - $ref: '#/parameters/EndDateQueryParam'

      responses:
        200:
          description: A list of energy readings.
          schema:
            type: array
            items:
              $ref: '#/definitions/EnergyReading'
        400:
          $ref: '#/responses/ErrorResponse'
        404:
          $ref: '#/responses/ErrorResponse'

definitions:
  EnergyReading:
    type: object
    properties:
      src:
        description: Source and software version of the device.
        type: string
      dsb:
        description: Days since birth. The number of days since the device started up.
        type: integer
      time:
        description: The date and time the reading was recorded.
        type: string
      tmprf:
        description: The temperature in degrees Fahrenheit at the time of the reading.
        type: number
      sensor:
        description: The ID of the sensor that took the reading.
        type: integer
      device_id:
        description: ID for the device that took the reading.
        type: string
      ch1_watts:
        description: The power in watts read from channel 1.
        type: integer
      ch2_watts:
        description: The power in watts read from channel 2.
        type: integer
      ch3_watts:
        description: The power in watts read from channel 3.
        type: integer

  Error:
    description: |
      A Problem Details object that describes the error encountered. See
      [RFC7807](https://tools.ietf.org/html/rfc7807) for more information.
    type: object
    properties:
      type:
        description: |
          A URI reference [RFC3986] that identifies the
          problem type.  This specification encourages that, when
          dereferenced, it provide human-readable documentation for the
          problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
          this member is not present, its value is assumed to be
          "about:blank".
        type: string
      title:
        description: |
          A short, human-readable summary of the problem type.  It SHOULD NOT
          change from occurrence to occurrence of the problem, except for
          purposes of localization (e.g., using proactive content negotiation;
          see [RFC7231], Section 3.4).
        type: string
      status:
        description: |
          The HTTP status code ([RFC7231], Section 6) generated by the origin
          server for this occurrence of the problem.
        type: integer
      detail:
        description: |
          A human-readable explanation specific to this occurrence of the
          problem.
        type: string
      instance:
        description: |
          A URI reference that identifies the specific occurrence of the
          problem.  It may or may not yield further information if
          dereferenced.
        type: string

parameters:
  StartDateQueryParam:
    name: startDate
    description: |
      A time that indicates all resources to retrieve will be created on or
      after the specified time. The value specified should conform to
      [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14)
      like `1970-01-01T12:00:00.000Z`. The default if not specified is one hour
      before the request was received.
    in: query
    type: string

  EndDateQueryParam:
    name: endDate
    description: |
      A time that indicates all resources to retrieve will be created before
      the specified time. The value specified should conform to
      [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14)
      like `1970-01-01T12:00:00.000Z`. The default if not specified is the time
      the request was received.
    in: query
    type: string

  LimitQueryParam:
    name: limit
    description: The maximum number of resources to return.
    in: query
    type: number

responses:
  ErrorResponse:
    description: An error has occurred.
    schema:
      $ref: '#/definitions/Error'
